{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "56a5786d-8d8d-421a-bb27-deaab8a95854",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q1. Ans \n",
    "\n",
    "An Exception is an error or event that happens during the execution of a program that disrupts the normal flow of the\n",
    "program's instructions. Whenever there is an error, Python generates an exception that could be handled.\n",
    "It basically prevents the program from getting crashed.\n",
    "\n",
    "\n",
    "Actually,An exception is an abnormal event that occurs during the execution of a program. Exceptions are usually caused\n",
    "by runtime errors, such as dividing by zero, trying to access an element in an array with an out-of-bounds index, or trying\n",
    "to access a file that does not exist. Exceptions are not syntax errors, but they can still prevent the program from running\n",
    "if they are not handled properly  whereas, A syntax error occurs when the structure of a program does not conform to the rules\n",
    "of the programming language. Syntax errors are usually detected by the compiler or interpreter when the program is being \n",
    "compiled or executed, and they prevent the program from running. Syntax errors are usually caused by mistakes in the source\n",
    "code, such as typos, omissions, or incorrect use of syntax.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2010dfea-8ed3-41bb-bcf1-8f5b6e21a6c3",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q2. Ans\n",
    "\n",
    "Simply, the program will be crashed or not execute.\n",
    "\n",
    "for example\n",
    "\n",
    "def calc():\n",
    "    \n",
    "    a=10/0\n",
    "    \n",
    "    return(a)\n",
    "\n",
    "calc()     # division by zero error will be occured."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dd4b3d56-3e2c-48ee-b251-dece4153c145",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q3. Ans\n",
    "\n",
    "The try and except block in Python is used to catch and handle exceptions.\n",
    "\n",
    "\n",
    "For example \n",
    "\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename=\"error.log\",level=logging.ERROR)\n",
    "\n",
    "\n",
    "try:\n",
    "    \n",
    "    a=10/0\n",
    "    \n",
    "except ZeroDivisionError as err:\n",
    "    \n",
    "    logging.error(\"I am trying to handle zero division error{}\".format(err))\n",
    "    \n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fa55732b-06b8-4c87-bd98-143c7facd093",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q4. Ans\n",
    "\n",
    "a)\n",
    "\n",
    "try block will test the excepted error to occur and  If there is no exception then else block will be executed.\n",
    "\n",
    "for example\n",
    "\n",
    "# Case1(with error)\n",
    "\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename=\"error.log\",level=logging.ERROR)\n",
    "\n",
    "\n",
    "try:\n",
    "    \n",
    "    a=10/0\n",
    "    \n",
    "except ZeroDivisionError as err:\n",
    "    \n",
    "    logging.error(\"I am trying to handle zero division error{}\".format(err))   # will occur zero division error \n",
    "                                                                               # and else block won't execute\n",
    "    \n",
    "else:\n",
    "    \n",
    "    print(\"Code run Successfully\")   \n",
    "    \n",
    "    \n",
    "    \n",
    "# Case2\n",
    "\n",
    "import logging\n",
    "\n",
    "logging.basicConfig(filename=\"error.log\",level=logging.ERROR)\n",
    "\n",
    "\n",
    "try:\n",
    "    \n",
    "    a=10+5\n",
    "    \n",
    "except ZeroDivisionError as err:\n",
    "    \n",
    "    logging.error(\"I am trying to handle zero division error{}\".format(err))\n",
    "    \n",
    "else:\n",
    "    \n",
    "    print(\"Code run Successfully\")    # else block execute successfully\n",
    "\n",
    "\n",
    "\n",
    "    \n",
    "    \n",
    "b)\n",
    "\n",
    "Finally block always gets executed either exception is generated or not.\n",
    "\n",
    "for example \n",
    "\n",
    "\n",
    "try:\n",
    "    \n",
    "    a=10/0\n",
    "    \n",
    "finally:\n",
    "    \n",
    "    print(5+9) \n",
    "\n",
    "\n",
    "    \n",
    "    \n",
    "c)\n",
    "\n",
    "The raise keyword is used to raise an exception.\n",
    "\n",
    "We can define what kind of error to raise, and the text to print to the user.\n",
    "\n",
    "\n",
    "for example\n",
    "\n",
    "a = 5\n",
    "\n",
    "if a % 2 != 0:\n",
    "\traise Exception(\"The number shouldn't be an odd integer\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7c4a2cd8-f08f-423c-b0cb-60b6aa188f78",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q5. Ans\n",
    "\n",
    "Custom Exceptions is a user defined Exception class. we can define custom exceptions by creating a new class that is derived\n",
    "from the built-in Exception class.\n",
    "\n",
    "\n",
    "\n",
    "because it provide Greater Code Trace-ability,Greater Code Usability,Improved Exception Handling,Ease in Debugging,etc\n",
    "\n",
    "for example  age validation \n",
    "\n",
    "\n",
    "\n",
    "class validateage(Exception):\n",
    "    \n",
    "    def __init__(self , msg) : \n",
    "        self.msg = msg\n",
    "        \n",
    "def validaetage(age) : \n",
    "    if age < 0 :\n",
    "        raise validateage(\"Entered age is negative \" )\n",
    "    elif age > 200 : \n",
    "        raise validateage(\"Enterd age is very very high \" )\n",
    "    else :\n",
    "        print(\"age is valid\" )\n",
    "        \n",
    "try :\n",
    "    age = int(input(\"enter your age\" ))\n",
    "    validaetage(age)\n",
    "except validateage as e :\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "360e2791-ae64-45bb-acf3-29e27a2c1ad0",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q6. Ans\n",
    "\n",
    "\n",
    "class valid_mob_no(Exception):      # creating custom exception\n",
    "    \n",
    "    def __init__(self , msg) : \n",
    "        self.msg = msg\n",
    "        \n",
    "def mob_no(n) : \n",
    "    if len(n) >10 :\n",
    "        raise valid_mob_no(\"Entered Mob.No is greater than 10 digits\" )\n",
    "    elif len(n) < 10: \n",
    "        raise valid_mob_no(\"Entered Mob.No os less than 10 digits\" )\n",
    "    else :\n",
    "        if len(n)==10:\n",
    "            \n",
    "            print(\"Valid Mobile Number\" )\n",
    "        \n",
    "try :\n",
    "    n = input(\"Enter Your Mob. No\" )\n",
    "    mob_no(n)\n",
    "except valid_mob_no as err :\n",
    "    print(err)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
